In [3]:
import numpy as np
A = np.array([[1,1,0], [0,2,1], [0,0,3]])


In [21]:
A

array([[1, 1, 0],
       [0, 2, 1],
       [0, 0, 3]])

In [22]:
np.sum(A)

8

In [30]:
A_col= np.sum(A, axis=0)
A_col

array([1, 3, 4])

In [14]:
U, S, Vt = np.linalg.svd(A)

In [6]:
U

array([[ 0.11309038, -0.54551277,  0.83043746],
       [ 0.49267857, -0.69502219, -0.52365254],
       [ 0.86283161,  0.4683588 ,  0.19016213]])

In [7]:
S

array([3.27307286, 2.13263749, 0.85956463])

In [8]:
Vt

array([[ 0.03455174,  0.3356013 ,  0.94137025],
       [-0.25579255, -0.90758845,  0.33294652],
       [ 0.96611405, -0.25229938,  0.05448555]])

In [16]:
np.dot(U, np.dot(np.diag(S),Vt))

array([[ 1.00000000e+00,  1.00000000e+00, -8.49065513e-17],
       [ 3.00907601e-16,  2.00000000e+00,  1.00000000e+00],
       [-4.51966984e-17, -5.35415380e-16,  3.00000000e+00]])

In [19]:
A_ = np.dot(U, np.dot(np.diag(S),Vt))
A_

array([[ 1.00000000e+00,  1.00000000e+00, -8.49065513e-17],
       [ 3.00907601e-16,  2.00000000e+00,  1.00000000e+00],
       [-4.51966984e-17, -5.35415380e-16,  3.00000000e+00]])

In [20]:
print(np.round(A,3))

[[1 1 0]
 [0 2 1]
 [0 0 3]]


In [9]:
np.dot(A,Vt.T)

array([[ 0.37015305, -1.16338099,  0.71381467],
       [ 1.61257285, -1.48223038, -0.4501132 ],
       [ 2.82411074,  0.99883955,  0.16345664]])

In [11]:
np.diag(S)

array([[3.27307286, 0.        , 0.        ],
       [0.        , 2.13263749, 0.        ],
       [0.        , 0.        , 0.85956463]])

In [12]:
np.dot(U,np.diag(S))

array([[ 0.37015305, -1.16338099,  0.71381467],
       [ 1.61257285, -1.48223038, -0.4501132 ],
       [ 2.82411074,  0.99883955,  0.16345664]])

In [25]:
SS = np.array ([[3.27307286, 0, 0], [0,2.13263749,0], [0,0,0.85956463]])

In [26]:
SS

array([[3.27307286, 0.        , 0.        ],
       [0.        , 2.13263749, 0.        ],
       [0.        , 0.        , 0.85956463]])

In [16]:
np.dot(U, SS)

array([[ 0.37015305, -1.16338099,  0.71381467],
       [ 1.61257285, -1.48223038, -0.4501132 ],
       [ 2.82411074,  0.99883954,  0.16345664]])

In [33]:
np.dot(U[0,:], U[1,:])

3.885780586188048e-16

In [28]:
U[:,0]

array([0.11309038, 0.49267857, 0.86283161])

In [29]:
U[:,1]

array([-0.54551277, -0.69502219,  0.4683588 ])

In [36]:
U[:,0] * U[:,1]

array([-0.06169225, -0.34242254,  0.40411478])

In [37]:
np.sum([0,1,2])

3

In [38]:
np.sum([-0.06169225, -0.34242254,  0.40411478])

-9.999999994736442e-09

In [40]:
np.dot(np.dot(U,SS),V.T)

array([[ 0.29432115,  1.19885087,  0.69002294],
       [-0.86544442,  0.78290743,  1.90737042],
       [ 0.58666302, -1.57449939,  2.48531249]])

In [29]:
# coding: utf-8
import sys
sys.path.append('..')
from common.util import preprocess, create_co_matrix, most_similar


text = 'You say goodbye and I say hello. I say hello. You say goodbye.'
corpus, word_to_id, id_to_word = preprocess(text)
vocab_size = len(word_to_id)
C = create_co_matrix(corpus, vocab_size)
print(corpus)
print(C)
print("C: " + str(np.sum(C)))

most_similar('you', word_to_id, id_to_word, C, top=5)




[0 1 2 3 4 1 5 6 4 1 5 6 0 1 2 6]
[[0 2 0 0 0 0 1]
 [2 0 2 0 2 2 0]
 [0 2 0 1 0 0 1]
 [0 0 1 0 1 0 0]
 [0 2 0 1 0 0 1]
 [0 2 0 0 0 0 2]
 [1 0 1 0 1 2 0]]
C: 30

[query] you
 hello: 0.9486832904537711
 goodbye: 0.9128709213660141
 i: 0.9128709213660141
 say: 0.0
 and: 0.0


In [31]:
# coding: utf-8
import sys
sys.path.append('..')
import numpy as np
from common.util import preprocess, create_co_matrix, cos_similarity, ppmi


text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
vocab_size = len(word_to_id)
C = create_co_matrix(corpus, vocab_size)
W = ppmi(C)

np.set_printoptions(precision=3)  # 유효 자릿수를 세 자리로 표시
print('동시발생 행렬')
print(C)
print('-'*50)
print('PPMI')
print(W)

동시발생 행렬
[[0 1 0 0 0 0 0]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 1 0 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 0 1 0]]
--------------------------------------------------
PPMI
[[0.    1.807 0.    0.    0.    0.    0.   ]
 [1.807 0.    0.807 0.    0.807 0.807 0.   ]
 [0.    0.807 0.    1.807 0.    0.    0.   ]
 [0.    0.    1.807 0.    1.807 0.    0.   ]
 [0.    0.807 0.    1.807 0.    0.    0.   ]
 [0.    0.807 0.    0.    0.    0.    2.807]
 [0.    0.    0.    0.    0.    2.807 0.   ]]


In [32]:
# coding: utf-8
import sys
sys.path.append('..')
import numpy as np
from common.util import preprocess, create_co_matrix, cos_similarity, ppmi


text = 'You say goodbye and I say hello. You say goodbye. I say hello. You and I say hello and goodbye'
corpus, word_to_id, id_to_word = preprocess(text)
vocab_size = len(word_to_id)
C = create_co_matrix(corpus, vocab_size)
W = ppmi(C)

np.set_printoptions(precision=3)  # 유효 자릿수를 세 자리로 표시
print('동시발생 행렬')
print(C)
print('-'*50)
print('PPMI')
print(W)

동시발생 행렬
[[0 2 0 1 0 0 2]
 [2 0 2 0 3 3 0]
 [0 2 0 2 0 0 1]
 [1 0 2 0 2 1 0]
 [0 3 0 2 0 0 1]
 [0 3 0 1 0 0 2]
 [2 0 1 0 1 2 0]]
--------------------------------------------------
PPMI
[[0.    0.816 0.    0.553 0.    0.    1.553]
 [0.816 0.    0.816 0.    1.138 1.138 0.   ]
 [0.    0.816 0.    1.553 0.    0.    0.553]
 [0.553 0.    1.553 0.    1.29  0.29  0.   ]
 [0.    1.138 0.    1.29  0.    0.    0.29 ]
 [0.    1.138 0.    0.29  0.    0.    1.29 ]
 [1.553 0.    0.553 0.    0.29  1.29  0.   ]]
